### PR TITLE
Create .gitignore so that all the random Python / C cache and Distributions/packagings/installers/tests/translations/venvs/docs and IDE sh*t don't go in the repo or git

### PR DESCRIPTION
**Pull request by hanwenzhu**
Yep. Just like what the title says. Pretty self-explanatory.
@davidmaamoaix

### CODE REVIEW

**Comment by hanwenzhu** [comment]
@davidmaamoaix
Do you ever read notifications?

**Comment by linxuanm** [comment]
I do have .gitignore though just didn't add it to the commit ;)

**Comment by linxuanm** [comment]
and no I don't read notifications ;)

**Comment by linxuanm** [comment]
and JasonSheep is probably not gonna be worked on for quite a while so yeah ;)

**Pull request closed without merging**
